// src/platform/Ingot.Platform.Web/src/App.jsx
import { Dialog, DialogBackdrop, DialogPanel, Menu, MenuButton, MenuItem, MenuItems } from "@headlessui/react";
import {
  BoltIcon,
  ChartBarIcon,
  ChatBubbleLeftRightIcon,
  CircleStackIcon,
  ClipboardDocumentCheckIcon,
  Cog6ToothIcon,
  MagnifyingGlassIcon,
  RectangleGroupIcon,
  Squares2X2Icon,
  UserCircleIcon,
  WrenchScrewdriverIcon,
  XMarkIcon,
} from "@heroicons/react/24/outline";
import { useMemo, useState } from "react";
import { Link, Navigate, Route, Routes, useLocation, useNavigate } from "react-router-dom";
import * as Pages from "./pages";
import { cx } from "./ui/components";

const sections = [
  { id: "workbench", label: "工作台", icon: Squares2X2Icon, path: "/workbench", items: [] },
  { id: "chat", label: "AI 助手", icon: ChatBubbleLeftRightIcon, path: "/chat", items: [] },
  {
    id: "operations", label: "运行与追溯", icon: BoltIcon, path: "/cycles", items: [
      ["/cycles", "运行记录"], ["/events", "生产事件"], ["/production/changeover", "生产切换"],
      ["/production/tooling-installations", "工装装卸"],
    ],
  },
  {
    id: "quality", label: "质量管理", icon: ClipboardDocumentCheckIcon, path: "/inspections", items: [
      ["/inspections", "质量任务"], ["/quality-analysis", "质量分析"],
      ["/configuration/inspection-definitions", "检测定义"], ["/configuration/quality-plans", "质量方案"],
    ],
  },
  {
    id: "analysis", label: "分析中心", icon: ChartBarIcon, path: "/comparisons", items: [
      ["/comparisons", "历史对比"], ["/data-quality", "数据健康"], ["/process-improvement", "工艺改进"],
      ["/configuration/process-analysis-plans", "分析方案"],
    ],
  },
  {
    id: "data", label: "数据资产", icon: CircleStackIcon, path: "/explorer", items: [
      ["/explorer", "对象目录"], ["/configuration/process-data-models", "工艺数据模型"],
      ["/configuration/recipe-versions", "配方版本"], ["/configuration/acquisition-profiles", "采集任务"],
      ["/edges", "采集节点"],
    ],
  },
  {
    id: "tooling", label: "工装管理", icon: WrenchScrewdriverIcon, path: "/configuration/components", items: [
      ["/configuration/component-types", "组件类型"], ["/configuration/components", "组件台账"],
      ["/configuration/tooling-types", "工装类型"], ["/configuration/tooling-assemblies", "工装组合"],
    ],
  },
  {
    id: "administration", label: "系统管理", icon: Cog6ToothIcon, path: "/platform-metrics", items: [
      ["/platform-metrics", "平台指标"], ["/subscriptions", "事件订阅"], ["/logs", "运行日志"],
    ],
  },
];

const pageDetails = {
  "/workbench": ["工作台", "生产、质量与数据状态"],
  "/chat": ["Ingot Chat", "查询与分析已保存的生产数据"],
  "/explorer": ["对象目录", "从运行对象进入数据、上下文与关联关系"],
  "/cycles": ["运行记录", "查看生产周期及其数据、工艺与质量上下文"],
  "/events": ["生产事件", "查询、追溯并关联运行上下文"],
  "/production/changeover": ["生产切换", "让设备、产品、配方和已装工装对接下来的周期生效"],
  "/production/tooling-installations": ["工装装卸", "记录工装组合版本在设备上的装入与卸下区间"],
  "/inspections": ["质量任务", "处理视觉检查、人工质检与原图复核"],
  "/quality-analysis": ["质量分析", "按产品、配方、运行对象和分析范围查看质量结果"],
  "/comparisons": ["历史对比", "比较同类生产周期、运行段或时间窗口"],
  "/data-quality": ["数据健康", "检查运行对象的数据范围、采样连续性与周期完整性"],
  "/process-improvement": ["工艺改进", "管理模型、调查试验、现场知识与参数建议闭环"],
  "/configuration/process-analysis-plans": ["分析方案", "配置分析范围、对齐方式、质量分组和数据项"],
  "/configuration/process-data-models": ["工艺数据模型", "定义采集数据项、配方参数结构和工艺阶段"],
  "/configuration/recipe-versions": ["配方版本", "维护引用数据模型的完整配方有效值"],
  "/configuration/acquisition-profiles": ["采集任务", "管理数据源连接、采集对象、字段映射与发布版本"],
  "/configuration/inspection-definitions": ["检测定义", "定义要检测的特性、录入类型和判定规则"],
  "/configuration/quality-plans": ["质量方案", "配置产品适用的检测项目与复核规则"],
  "/configuration/component-types": ["组件类型", "配置组件台账的分类来源"],
  "/configuration/components": ["组件台账", "登记可更换、复用和追溯的物理组件"],
  "/configuration/tooling-types": ["工装类型", "配置装配位置及允许的组件类型"],
  "/configuration/tooling-assemblies": ["工装组合", "维护工装身份与不可变组件组合版本"],
  "/edges": ["采集节点", "查看现场采集节点及运行状态"],
  "/platform-metrics": ["平台指标", "查看平台与边缘节点运行指标"],
  "/subscriptions": ["事件订阅", "维护向外部系统投递的事件订阅"],
  "/logs": ["运行日志", "查询平台运行记录"],
};

export default function App() {
  const location = useLocation();
  const navigate = useNavigate();
  const [mobileOpen, setMobileOpen] = useState(false);
  const section = useMemo(
    () => sections.find(item => item.path === location.pathname || item.items.some(([path]) => path === location.pathname)) ?? sections[0],
    [location.pathname],
  );
  const page = pageDetails[location.pathname] ?? ["Ingot", "制造数据平台"];

  return (
    <div className="min-h-screen bg-slate-50 text-slate-900">
      <header className="fixed inset-x-0 top-0 z-50 flex h-16 items-stretch border-b border-slate-200 bg-white/95 shadow-sm backdrop-blur">
        <button className="flex w-55 shrink-0 items-center gap-3 border-r border-slate-100 px-5 text-left" onClick={() => navigate("/workbench")}>
          <span className="grid size-9 place-items-center rounded-xl bg-amber-50 ring-1 ring-amber-200">
            <img src="/ingot-mark.svg" alt="" className="size-7" />
          </span>
          <span className="hidden sm:grid">
            <strong className="text-base leading-5 text-slate-950">Ingot</strong>
            <small className="text-[10px] text-slate-500">制造数据平台</small>
          </span>
        </button>
        <nav className="flex min-w-0 flex-1 overflow-x-auto" aria-label="全局导航">
          {sections.map(item => {
            const Icon = item.icon;
            const active = item.id === section.id;
            return (
              <Link
                key={item.id}
                to={item.path}
                className={cx(
                  "relative flex shrink-0 items-center gap-2 px-3 text-xs font-medium transition md:px-4 md:text-sm",
                  active ? "bg-blue-50/70 text-blue-700 after:absolute after:inset-x-4 after:bottom-0 after:h-0.5 after:bg-blue-600" : "text-slate-600 hover:bg-slate-50 hover:text-slate-950",
                )}
              >
                <Icon className="size-4.5" />
                <span>{item.label}</span>
              </Link>
            );
          })}
        </nav>
        <button className="hidden items-center gap-2 border-l border-slate-100 px-4 text-sm text-slate-600 hover:bg-slate-50 md:flex" onClick={() => navigate("/explorer")}>
          <MagnifyingGlassIcon className="size-5" />搜索
        </button>
        <Menu as="div" className="relative flex border-l border-slate-100">
          <MenuButton className="grid w-14 place-items-center text-slate-600 hover:bg-slate-50" aria-label="用户菜单">
            <UserCircleIcon className="size-6" />
          </MenuButton>
          <MenuItems transition anchor="bottom end" className="z-100 mt-2 w-48 origin-top-right rounded-xl border border-slate-200 bg-white p-1 text-sm shadow-xl transition data-closed:scale-95 data-closed:opacity-0">
            <MenuItem><a href="/health" className="block rounded-lg px-3 py-2 text-slate-700 data-focus:bg-slate-100">服务健康状态</a></MenuItem>
            <MenuItem><a href="https://docs.ingotstack.com/zh" className="block rounded-lg px-3 py-2 text-slate-700 data-focus:bg-slate-100">产品文档</a></MenuItem>
          </MenuItems>
        </Menu>
      </header>

      <div className="pt-16">
        {section.items.length > 0 && (
          <aside className="fixed inset-y-16 left-0 z-30 hidden w-55 border-r border-slate-200 bg-white lg:block">
            <div className="flex h-16 items-center gap-2 border-b border-slate-100 px-5">
              <section.icon className="size-5 text-blue-600" />
              <strong className="text-sm">{section.label}</strong>
            </div>
            <nav className="grid gap-1 p-3" aria-label={`${section.label}导航`}>
              {section.items.map(([path, label]) => (
                <Link key={path} to={path} className={cx("rounded-lg px-3 py-2.5 text-sm", path === location.pathname ? "bg-blue-50 font-medium text-blue-700" : "text-slate-600 hover:bg-slate-50 hover:text-slate-950")}>
                  {label}
                </Link>
              ))}
            </nav>
          </aside>
        )}

        <div className={cx(section.items.length > 0 && "lg:ml-55")}>
          <div className="sticky top-16 z-20 flex min-h-16 items-center gap-3 border-b border-slate-200 bg-white/90 px-4 backdrop-blur sm:px-6">
            {section.items.length > 0 && (
              <button className="grid size-9 place-items-center rounded-lg text-slate-600 hover:bg-slate-100 lg:hidden" onClick={() => setMobileOpen(true)} aria-label="打开模块导航">
                <RectangleGroupIcon className="size-5" />
              </button>
            )}
            <div>
              <p className="font-semibold text-slate-950">{page[0]}</p>
              <p className="text-xs text-slate-500">{page[1]}</p>
            </div>
          </div>
          <main className="mx-auto w-full max-w-[1600px] p-4 sm:p-6">
            <AppRoutes />
          </main>
        </div>
      </div>

      <Dialog open={mobileOpen} onClose={setMobileOpen} className="relative z-80 lg:hidden">
        <DialogBackdrop className="fixed inset-0 bg-slate-950/30" />
        <DialogPanel className="fixed inset-y-0 left-0 w-72 bg-white shadow-2xl">
          <div className="flex h-16 items-center justify-between border-b border-slate-200 px-4">
            <strong>{section.label}</strong>
            <button className="grid size-9 place-items-center rounded-lg hover:bg-slate-100" onClick={() => setMobileOpen(false)} aria-label="关闭模块导航">
              <XMarkIcon className="size-5" />
            </button>
          </div>
          <nav className="grid gap-1 p-3">
            {section.items.map(([path, label]) => (
              <Link key={path} to={path} onClick={() => setMobileOpen(false)} className={cx("rounded-lg px-3 py-3 text-sm", path === location.pathname ? "bg-blue-50 font-medium text-blue-700" : "text-slate-700 hover:bg-slate-50")}>
                {label}
              </Link>
            ))}
          </nav>
        </DialogPanel>
      </Dialog>
    </div>
  );
}

function AppRoutes() {
  return (
    <Routes>
      <Route path="/" element={<Navigate to="/workbench" replace />} />
      <Route path="/workbench" element={<Pages.WorkbenchPage />} />
      <Route path="/chat" element={<Pages.ChatPage />} />
      <Route path="/explorer" element={<Pages.ObjectExplorerPage />} />
      <Route path="/cycles" element={<Pages.CyclesPage />} />
      <Route path="/events" element={<Pages.EventsPage />} />
      <Route path="/production/changeover" element={<Pages.ProductionSetupPage section="context" />} />
      <Route path="/production/tooling-installations" element={<Pages.ProductionSetupPage section="installation" />} />
      <Route path="/configuration/component-types" element={<Pages.ProductionSetupPage section="componentType" />} />
      <Route path="/configuration/components" element={<Pages.ProductionSetupPage section="component" />} />
      <Route path="/configuration/tooling-types" element={<Pages.ProductionSetupPage section="type" />} />
      <Route path="/configuration/tooling-assemblies" element={<Pages.ProductionSetupPage section="assembly" />} />
      <Route path="/production-setup" element={<Navigate to="/production/changeover" replace />} />
      <Route path="/inspections" element={<Pages.InspectionsPage />} />
      <Route path="/quality-analysis" element={<Pages.QualityAnalysisPage />} />
      <Route path="/quality-plans" element={<Navigate to="/configuration/quality-plans" replace />} />
      <Route path="/configuration/inspection-definitions" element={<Pages.InspectionDefinitionsPage />} />
      <Route path="/configuration/quality-plans" element={<Pages.QualityPlansPage />} />
      <Route path="/comparisons" element={<Pages.CycleComparisonPage />} />
      <Route path="/data-quality" element={<Pages.DataQualityPage />} />
      <Route path="/process-improvement" element={<Pages.ProcessImprovementPage />} />
      <Route path="/configuration/process-analysis-plans" element={<Pages.ProcessAnalysisPlansPage />} />
      <Route path="/profiles" element={<Navigate to="/configuration/process-data-models" replace />} />
      <Route path="/configuration/process-data-models" element={<Pages.ProcessDataModelsPage />} />
      <Route path="/configuration/recipe-versions" element={<Pages.RecipeVersionsPage />} />
      <Route path="/configuration/acquisition-profiles" element={<Pages.AcquisitionProfilesPage />} />
      <Route path="/edges" element={<Pages.EdgesPage />} />
      <Route path="/platform-metrics" element={<Pages.MetricsPage />} />
      <Route path="/subscriptions" element={<Pages.SubscriptionsPage />} />
      <Route path="/logs" element={<Pages.LogsPage />} />
      <Route path="*" element={<Pages.NotFoundPage />} />
    </Routes>
  );
}

// src/platform/Ingot.Platform.Web/src/App.vue
<template>
  <el-config-provider :locale="zhCn">
    <div class="app-shell">
      <header class="global-header">
        <button type="button" class="brand" aria-label="返回工作台" @click="router.push('/workbench')">
          <span class="brand-icon"><img src="/ingot-mark.svg" alt=""></span>
          <span class="brand-copy"><strong>Ingot</strong><small>制造数据平台</small></span>
        </button>

        <nav class="global-nav" aria-label="全局导航">
          <button
            v-for="section in navigationSections"
            :key="section.id"
            type="button"
            :class="{ active: currentSection.id === section.id }"
            :aria-current="currentSection.id === section.id ? 'page' : undefined"
            @click="openSection(section)"
          >
            <el-icon><component :is="section.icon" /></el-icon>
            <span>{{ section.label }}</span>
          </button>
        </nav>

        <button type="button" class="global-search" @click="router.push('/explorer')">
          <el-icon><Search /></el-icon><span>搜索数据</span>
        </button>
      </header>

      <div class="body-shell" :class="{ 'without-context-nav': !hasContextNavigation }">
        <button
          v-if="isMobile && contextNavigationOpen"
          type="button"
          class="context-backdrop"
          aria-label="关闭导航"
          @click="contextNavigationOpen = false"
        />

        <aside
          v-if="hasContextNavigation"
          class="context-sidebar"
          :class="{ 'is-open': contextNavigationOpen }"
        >
          <div class="context-title">
            <el-icon><component :is="currentSection.icon" /></el-icon>
            <strong>{{ currentSection.label }}</strong>
          </div>
          <nav aria-label="当前模块导航">
            <RouterLink
              v-for="item in currentSection.items"
              :key="item.path"
              :to="item.path"
              :class="{ active: route.path === item.path }"
              @click="contextNavigationOpen = false"
            >
              <span>{{ item.label }}</span>
            </RouterLink>
          </nav>
        </aside>

        <section class="workspace-shell">
          <header class="workspace-header">
            <button
              v-if="isMobile && hasContextNavigation"
              type="button"
              class="context-trigger"
              aria-label="打开当前模块导航"
              @click="contextNavigationOpen = true"
            >
              <el-icon><Menu /></el-icon>
            </button>
            <div class="page-heading">
              <strong>{{ currentPage.title }}</strong>
              <span>{{ currentPage.description }}</span>
            </div>
          </header>

          <main class="app-main">
            <router-view />
          </main>
        </section>
      </div>
    </div>
  </el-config-provider>
</template>

<script setup>
import { computed, onBeforeUnmount, onMounted, ref, watch } from "vue";
import { useRoute, useRouter } from "vue-router";
import {
  ChatDotRound,
  DataAnalysis,
  DocumentChecked,
  FolderOpened,
  Guide,
  HomeFilled,
  Menu,
  Search,
  Setting,
  Tools,
} from "@element-plus/icons-vue";
import zhCn from "element-plus/dist/locale/zh-cn.mjs";

const route = useRoute();
const router = useRouter();
const isMobile = ref(window.innerWidth <= 900);
const contextNavigationOpen = ref(false);

const navigationSections = [
  { id: "workbench", label: "工作台", icon: HomeFilled, path: "/workbench", items: [] },
  { id: "chat", label: "AI 助手", icon: ChatDotRound, path: "/chat", items: [] },
  {
    id: "operations", label: "运行与追溯", icon: Guide, path: "/cycles", items: [
      { path: "/cycles", label: "运行记录" },
      { path: "/events", label: "生产事件" },
      { path: "/production/changeover", label: "生产切换" },
      { path: "/production/tooling-installations", label: "工装装卸" },
    ],
  },
  {
    id: "quality", label: "质量管理", icon: DocumentChecked, path: "/inspections", items: [
      { path: "/inspections", label: "质量任务" },
      { path: "/quality-analysis", label: "质量分析" },
      { path: "/configuration/inspection-definitions", label: "检测定义" },
      { path: "/configuration/quality-plans", label: "质量方案" },
    ],
  },
  {
    id: "analysis", label: "分析中心", icon: DataAnalysis, path: "/comparisons", items: [
      { path: "/comparisons", label: "历史对比" },
      { path: "/data-quality", label: "数据健康" },
      { path: "/configuration/process-analysis-plans", label: "分析方案" },
    ],
  },
  {
    id: "data", label: "数据资产", icon: FolderOpened, path: "/explorer", items: [
      { path: "/explorer", label: "对象目录" },
      { path: "/configuration/process-data-models", label: "工艺数据模型" },
      { path: "/configuration/recipe-versions", label: "配方版本" },
      { path: "/configuration/acquisition-profiles", label: "采集任务" },
      { path: "/edges", label: "采集节点" },
    ],
  },
  {
    id: "tooling", label: "工装管理", icon: Tools, path: "/configuration/components", items: [
      { path: "/configuration/component-types", label: "组件类型" },
      { path: "/configuration/components", label: "组件台账" },
      { path: "/configuration/tooling-types", label: "工装类型" },
      { path: "/configuration/tooling-assemblies", label: "工装组合" },
    ],
  },
  {
    id: "administration", label: "系统管理", icon: Setting, path: "/platform-metrics", items: [
      { path: "/platform-metrics", label: "平台指标" },
      { path: "/subscriptions", label: "事件订阅" },
      { path: "/logs", label: "运行日志" },
    ],
  },
];

const pageDetails = {
  "/workbench": { title: "工作台", description: "生产、质量与数据状态" },
  "/chat": { title: "Ingot Chat", description: "查询与分析已保存的生产数据" },
  "/explorer": { title: "对象目录", description: "从运行对象进入数据、上下文与关联关系" },
  "/cycles": { title: "运行记录", description: "查看生产周期及其数据、工艺与质量上下文" },
  "/production/changeover": { title: "生产切换", description: "让设备、产品、配方和已装工装对接下来的周期生效" },
  "/production/tooling-installations": { title: "工装装卸", description: "记录工装组合版本在设备上的装入与卸下区间" },
  "/configuration/component-types": { title: "组件类型", description: "配置组件台账的分类来源" },
  "/configuration/components": { title: "组件台账", description: "登记可更换、复用和追溯的物理组件" },
  "/configuration/tooling-types": { title: "工装类型", description: "配置装配位置及允许的组件类型" },
  "/configuration/tooling-assemblies": { title: "工装组合", description: "维护工装身份与不可变组件组合版本" },
  "/events": { title: "生产事件", description: "查询、追溯并关联运行上下文" },
  "/inspections": { title: "质量任务", description: "处理视觉检查、人工质检与原图复核" },
  "/quality-analysis": { title: "质量分析", description: "按产品、配方、运行对象和分析范围查看质量结果" },
  "/comparisons": { title: "历史对比", description: "比较同类生产周期、运行段或时间窗口" },
  "/data-quality": { title: "数据健康", description: "检查运行对象的数据范围、采样连续性与周期完整性" },
  "/configuration/process-data-models": { title: "工艺数据模型", description: "定义采集数据项、配方参数结构和工艺阶段" },
  "/configuration/recipe-versions": { title: "配方版本", description: "维护引用数据模型的完整配方有效值" },
  "/configuration/acquisition-profiles": { title: "采集任务", description: "管理数据源连接、采集对象、字段映射与发布版本" },
  "/configuration/process-analysis-plans": { title: "分析方案", description: "配置分析范围、对齐方式、质量分组和数据项" },
  "/configuration/inspection-definitions": { title: "检测定义", description: "定义要检测的特性、录入类型和判定规则" },
  "/configuration/quality-plans": { title: "质量方案", description: "配置产品适用的检测项目与复核规则" },
  "/edges": { title: "采集节点", description: "查看现场采集节点及运行状态" },
  "/platform-metrics": { title: "平台指标", description: "查看平台与边缘节点运行指标" },
  "/subscriptions": { title: "事件订阅", description: "维护向外部系统投递的事件订阅" },
  "/logs": { title: "运行日志", description: "查询平台运行记录" },
};

const currentSection = computed(() => navigationSections.find(section => (
  route.path === section.path || section.items.some(item => item.path === route.path)
)) || navigationSections[0]);
const currentPage = computed(() => pageDetails[route.path] || { title: "Ingot", description: "制造数据平台" });
const hasContextNavigation = computed(() => currentSection.value.items.length > 0);

function openSection(section) {
  contextNavigationOpen.value = false;
  router.push(section.path);
}

function handleResize() {
  isMobile.value = window.innerWidth <= 900;
  if (!isMobile.value) contextNavigationOpen.value = false;
}

watch(() => route.path, () => { contextNavigationOpen.value = false; });
onMounted(() => window.addEventListener("resize", handleResize));
onBeforeUnmount(() => window.removeEventListener("resize", handleResize));
</script>

<style scoped>
.app-shell { min-height: 100vh; background: #f5f7fa; }
.global-header {
  position: fixed;
  z-index: 60;
  inset: 0 0 auto;
  display: flex;
  height: 60px;
  align-items: stretch;
  border-bottom: 1px solid #e5e9ef;
  background: rgba(255, 255, 255, .97);
  backdrop-filter: blur(12px);
}
.brand {
  display: flex;
  width: 216px;
  flex: 0 0 216px;
  align-items: center;
  gap: 10px;
  padding: 0 18px;
  border: 0;
  border-right: 1px solid #edf0f4;
  background: transparent;
  cursor: pointer;
  text-align: left;
}
.brand-icon { display: inline-flex; width: 34px; height: 34px; align-items: center; justify-content: center; border-radius: 9px; background: #fff7e6; box-shadow: inset 0 0 0 1px rgba(232, 137, 26, .18); }
.brand-icon img { display: block; width: 27px; height: 27px; }
.brand-copy { display: grid; gap: 1px; }
.brand-copy strong { color: #182238; font-size: 17px; }
.brand-copy small { color: #919bab; font-size: 10px; }
.global-nav { display: flex; min-width: 0; flex: 1; align-items: stretch; overflow-x: auto; scrollbar-width: none; }
.global-nav::-webkit-scrollbar { display: none; }
.global-nav button, .global-search {
  position: relative;
  display: inline-flex;
  flex: 0 0 auto;
  align-items: center;
  justify-content: center;
  gap: 6px;
  padding: 0 15px;
  border: 0;
  background: transparent;
  color: #5e697a;
  cursor: pointer;
  font: inherit;
  font-size: 13px;
}
.global-nav button::after { position: absolute; right: 16px; bottom: 0; left: 16px; height: 2px; border-radius: 2px 2px 0 0; background: transparent; content: ""; }
.global-nav button:hover, .global-nav button.active { color: #2878c8; background: #f7faff; }
.global-nav button.active { font-weight: 600; }
.global-nav button.active::after { background: #2878c8; }
.global-search { min-width: 112px; border-left: 1px solid #edf0f4; }
.global-search:hover { color: #2878c8; background: #f7faff; }
.body-shell { min-height: 100vh; padding-top: 60px; }
.context-sidebar {
  position: fixed;
  z-index: 40;
  top: 60px;
  bottom: 0;
  left: 0;
  width: 216px;
  border-right: 1px solid #e6eaf0;
  background: #fff;
}
.context-title { display: flex; height: 64px; align-items: center; gap: 9px; padding: 0 20px; border-bottom: 1px solid #edf0f4; color: #27344a; }
.context-title strong { font-size: 14px; }
.context-sidebar nav { display: grid; gap: 3px; padding: 14px 10px; }
.context-sidebar a { display: flex; height: 40px; align-items: center; padding: 0 15px; border-radius: 8px; color: #5d6879; font-size: 13px; text-decoration: none; }
.context-sidebar a:hover { color: #2e6fac; background: #f3f7fc; }
.context-sidebar a.active { color: #2878c8; background: #eaf4ff; font-weight: 600; }
.workspace-shell { min-width: 0; margin-left: 216px; }
.without-context-nav .workspace-shell { margin-left: 0; }
.workspace-header {
  position: sticky;
  z-index: 25;
  top: 60px;
  display: flex;
  height: 64px;
  align-items: center;
  gap: 10px;
  padding: 0 24px;
  border-bottom: 1px solid #e5e9ef;
  background: rgba(255, 255, 255, .94);
  backdrop-filter: blur(12px);
}
.page-heading { display: grid; gap: 2px; }
.page-heading strong { color: #182238; font-size: 16px; }
.page-heading span { color: #8d97a7; font-size: 11px; }
.context-trigger { display: none; width: 34px; height: 34px; align-items: center; justify-content: center; border: 0; border-radius: 8px; background: transparent; color: #5e697a; }
.app-main { width: 100%; max-width: 1600px; margin: 0 auto; padding: 24px; }
.context-backdrop { display: none; }

@media (max-width: 1180px) {
  .brand { width: 176px; flex-basis: 176px; }
  .global-nav button { padding: 0 11px; }
  .global-nav button .el-icon { display: none; }
}

@media (max-width: 900px) {
  .global-header { height: 56px; }
  .brand { width: 62px; flex-basis: 62px; justify-content: center; padding: 0; }
  .brand-copy { display: none; }
  .global-nav button { padding: 0 12px; }
  .global-nav button span { white-space: nowrap; }
  .global-search { min-width: 48px; padding: 0 14px; }
  .global-search span { display: none; }
  .body-shell { padding-top: 56px; }
  .context-sidebar { z-index: 55; top: 56px; transform: translateX(-100%); box-shadow: 10px 0 34px rgba(24, 38, 63, .16); transition: transform .2s ease; }
  .context-sidebar.is-open { transform: translateX(0); }
  .workspace-shell { margin-left: 0; }
  .workspace-header { top: 56px; height: 60px; padding: 0 12px; }
  .context-trigger { display: inline-flex; flex: 0 0 auto; }
  .app-main { padding: 14px 10px; }
  .context-backdrop { position: fixed; z-index: 50; inset: 56px 0 0; display: block; border: 0; background: rgba(17, 28, 47, .28); }
}
</style>
